In [1]:
import requests
import pandas as pd
from imdb_password import api_key

In [2]:
# Load your dataset
df_missing_year = pd.read_csv('./DataSets/Movie_missing_year.csv')

In [3]:
# Set up the API key and base URL
base_url = 'http://www.omdbapi.com/'

In [4]:
# Create a function to fetch the year from OMDb API
def fetch_year_from_omdb(title):
    params = {
        't': title,
        'apikey': api_key
    }
    response = requests.get(base_url, params=params)
    if response.status_code == 200:
        data = response.json()
        if data.get('Response') == 'True' and 'Year' in data:
            return data['Year']
    return None

In [5]:
# Apply the function to fill in missing years
df_missing_year['YEAR'] = df_missing_year['Title'].apply(fetch_year_from_omdb)

In [7]:
# Preview the updated DataFrame
df_missing_year

,YEAR,MovieID,Title,Genres_Western,Genres_War,Genres_Thriller,Genres_Sci-Fi,Genres_Romance,Genres_Mystery,Genres_Musical,...,Genres_Film-Noir,Genres_Fantasy,Genres_Drama,Genres_Documentary,Genres_Crime,Genres_Comedy,Genres_Children's,Genres_Animation,Genres_Adventure,Genres_Action
0,1931,12,Dracula,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1994,19,Ace Ventura,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1995,66,Lawnmower Man 2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2004,99,Heidi Fleiss,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1988,165,Die Hard,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,1986,3889,Highlander,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
193,2007–2011,3908,Urban Legends,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
194,2021–,3918,Hellbound,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
195,1992,3919,Hellraiser III,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
196,1999–2007,3945,Digimon,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# Save the updated DataFrame to a CSV
df_missing_year.to_csv('./DataSets/updated_movies.csv', index=False)