In [19]:
# Import the required modules
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [20]:
ratings_cluster_df = pd.read_csv(
    Path("../df_ratings_cluster_135.csv"), index_col="Title"
)

# Review the DataFrame
display(ratings_cluster_df.head())
display(ratings_cluster_df.tail())

,UserID,Gender,Age,Occupation,Rating,Genres_Western,Genres_War,Genres_Thriller,Genres_Sci-Fi,Genres_Romance,...,Genres_Fantasy,Genres_Drama,Genres_Documentary,Genres_Crime,Genres_Comedy,Genres_Children's,Genres_Animation,Genres_Adventure,Genres_Action,Cluster_Label_101
Title,,,,,,,,,,,,,,,,,,,,,
Showgirls,438,2,18,11,4,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,88
"Parent Trap, The",438,2,18,11,3,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,88
Rocky,438,2,18,11,3,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,88
Swiss Family Robinson,438,2,18,11,3,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,88
"20,000 Leagues Under the Sea",438,2,18,11,3,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,88

,UserID,Gender,Age,Occupation,Rating,Genres_Western,Genres_War,Genres_Thriller,Genres_Sci-Fi,Genres_Romance,...,Genres_Fantasy,Genres_Drama,Genres_Documentary,Genres_Crime,Genres_Comedy,Genres_Children's,Genres_Animation,Genres_Adventure,Genres_Action,Cluster_Label_101
Title,,,,,,,,,,,,,,,,,,,,,
Mission to Mars,1877,1,45,20,4,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,68
Romeo Must Die,1877,1,45,20,4,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,68
"Color of Paradise, The (Rang-e Khoda)",1877,1,45,20,3,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,68
Waking the Dead,1877,1,45,20,3,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,68
"Road to El Dorado, The",1877,1,45,20,3,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,68

In [21]:
# Split the data into X (features) and y (target)
# The y variable should focus on the target column
y = ratings_cluster_df['Gender']

# The X variable should include all features except the target
X = ratings_cluster_df.drop(columns=['Gender'])

In [22]:
# Split into testing and training sets using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [23]:
# Declare a logistic regression model.
# Apply a random_state of 9 to the model
logistic_regression_model = LogisticRegression(random_state=9)

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_train)

c:\Users\chris\anaconda3\envs\dev\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [24]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [25]:
# Create and save the training classification report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

           1       0.41      0.00      0.00    156795
           2       0.75      1.00      0.86    470562

    accuracy                           0.75    627357
   macro avg       0.58      0.50      0.43    627357
weighted avg       0.67      0.75      0.64    627357

In [26]:
# Create and save the testing classification report
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

           1       0.43      0.00      0.00     51749
           2       0.75      1.00      0.86    157371

    accuracy                           0.75    209120
   macro avg       0.59      0.50      0.43    209120
weighted avg       0.67      0.75      0.65    209120